global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-monitoring'

# Alertmanager konfiguratsiyasi
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Alert qoidalari
rule_files:
  - "alerts.yml"

# Monitoring targets
scrape_configs:
  # Prometheus o'zini monitoring qilish
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Server metrikalar (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'server-1'
      - targets: ['83.222.7.86:9100']
        labels:
            instance: 'Kim-Tex server'
      - targets: [ '195.158.31.106:9100' ]
        labels:
          instance: 'Camera.urdu.uz server'

  # Docker container monitoring (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Veb-saytlar monitoring (Blackbox Exporter)
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          # Bu yerga o'zingizning saytlaringizni qo'shing
          - https://camera.urdu.uz
          - https://urdu.uz
          # - https://sizning-saytingiz.uz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL sertifikat monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://camera.urdu.uz
          - https://urdu.uz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # TCP port monitoring
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          # Port tekshirish uchun
          - camera.urdu.uz:443
          - urdu.uz:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115